(()=>{
const c=document.getElementById('game'),x=c.getContext('2d'),$=id=>document.getElementById(id);
let W=0,H=0,run=false,last=0,turn=0,keys={},mx=0,depth=[],floor=1,kills=0,level=1,xp=0,need=100,flash=0,shake=0,msgT=0;
let map=[],doors=[],chests=[],enemies=[],drops=[],parts=[];
const p={x:1.5,y:1.5,a:0,hp:100,max:100,en:100,spd:1.8,dmg:34,cd:0,rate:.38,crit:.08};
const types=[{hp:55,spd:.65,dmg:8,col:'#71d66b',size:.38,xp:25},{hp:100,spd:.38,dmg:14,col:'#c5d85d',size:.48,xp:45},{hp:72,spd:.82,dmg:10,col:'#9d7cff',size:.4,xp:35}];
function resize(){W=c.clientWidth;H=c.clientHeight;let d=Math.min(2,devicePixelRatio||1);c.width=W*d;c.height=H*d;x.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
const rnd=(a,b)=>a+Math.random()*(b-a),cell=(a,b)=>map[b]?.[a]??1;
function doorAt(a,b){for(const d of doors)if(d.x===a&&d.y===b)return d;return null}
function solid(a,b){let v=cell(Math.floor(a),Math.floor(b));if(v===1)return true;if(v===2){let d=doorAt(Math.floor(a),Math.floor(b));return !d||d.open<.9}return false}
function los(ax,ay,bx,by){let dx=bx-ax,dy=by-ay,n=Math.ceil(Math.hypot(dx,dy)*10);for(let i=1;i<n;i++)if(solid(ax+dx*i/n,ay+dy*i/n))return false;return true}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.random()*(i+1)|0;[a[i],a[j]]=[a[j],a[i]]}return a}
function makeMap(){
 const w=23,h=23;map=Array.from({length:h},()=>Array(w).fill(1));
 const stack=[[1,1]];map[1][1]=0;
 while(stack.length){let [a,b]=stack[stack.length-1],ns=shuffle([[2,0],[-2,0],[0,2],[0,-2]]).filter(([dx,dy])=>a+dx>0&&b+dy>0&&a+dx<w-1&&b+dy<h-1&&map[b+dy][a+dx]===1);if(!ns.length){stack.pop();continue}let [dx,dy]=ns[0],nx=a+dx,ny=b+dy;map[b+dy/2][a+dx/2]=0;map[ny][nx]=0;stack.push([nx,ny])}
 for(let i=0;i<12;i++){let a=3+(Math.random()*8|0)*2,b=3+(Math.random()*8|0)*2;for(let yy=-1;yy<=1;yy++)for(let xx=-1;xx<=1;xx++)if(a+xx>0&&b+yy>0&&a+xx<w-1&&b+yy<h-1)map[b+yy][a+xx]=0}
 p.x=1.5;p.y=1.5;p.a=0;doors=[];chests=[];enemies=[];drops=[];parts=[];
 let cand=[];for(let b=2;b<h-2;b++)for(let a=2;a<w-2;a++)if(map[b][a]===0){let h1=cell(a-1,b)===0&&cell(a+1,b)===0&&cell(a,b-1)===1&&cell(a,b+1)===1,v1=cell(a,b-1)===0&&cell(a,b+1)===0&&cell(a-1,b)===1&&cell(a+1,b)===1;if(h1||v1)cand.push([a,b])}
 shuffle(cand);for(const q of cand.slice(0,5))if(Math.hypot(q[0]-.5-p.x,q[1]+.5-p.y)>3){map[q[1]][q[0]]=2;doors.push({x:q[0],y:q[1],open:0})}
 let open=[];for(let b=2;b<h-2;b++)for(let a=2;a<w-2;a++)if(map[b][a]===0&&Math.hypot(a+.5-p.x,b+.5-p.y)>3)open.push([a,b]);shuffle(open);
 for(const q of open.slice(0,5))chests.push({x:q[0],y:q[1],open:false});
 for(const q of open.slice(5,20))if(enemies.length<5+floor*2){let t=types[Math.random()*types.length|0],hp=t.hp*(1+floor*.12);enemies.push({x:q[0]+.5,y:q[1]+.5,hp,max:hp,spd:t.spd*(1+floor*.02),dmg:t.dmg*(1+floor*.08),col:t.col,size:t.size,xp:t.xp,atk:0})}
}
function wallColor(d,s){let v=Math.max(38,90-d*4),r=v+(s?5:0),g=v+(s?6:2),b=v+(s?7:4);return `rgb(${r|0},${g|0},${b|0})`}
function cast(){depth=new Array(200);let n=200,strip=W/n;x.fillStyle='#120d0c';x.fillRect(0,0,W,H/2);x.fillStyle='#181411';x.fillRect(0,H/2,W,H/2);for(let i=0;i<n;i++){let a=p.a-Math.PI/6+i/(n-1)*Math.PI/3,rx=Math.cos(a),ry=Math.sin(a),d=0,side=0,hit=1;for(let k=0;k<600&&d<18;k++){d+=.035;let xx=p.x+rx*d,yy=p.y+ry*d,v=cell(Math.floor(xx),Math.floor(yy));if(v===1||v===2){hit=v;let fx=xx-Math.floor(xx),fy=yy-Math.floor(yy);side=Math.min(fx,1-fx)<Math.min(fy,1-fy)?0:1;break}}let z=d*Math.cos(a-p.a);depth[i]=z;let hh=Math.min(H*1.7,H/z),top=(H-hh)/2;x.fillStyle=hit===2?'#76512f':wallColor(z,side);x.fillRect(i*strip,top,strip+1,hh);if(hit===1&&hh>90){x.fillStyle='rgba(20,17,16,.35)';let bh=Math.max(14,hh/6);for(let yy=top+bh;yy<top+hh;yy+=bh)x.fillRect(i*strip,yy,strip+1,1)}}}
function proj(o){let dx=o.x-p.x,dy=o.y-p.y,ca=Math.cos(p.a),sa=Math.sin(p.a),sx=dx*ca+dy*sa,sy=-dx*sa+dy*ca;if(sx<=.05)return null;let ang=Math.atan2(sy,sx);if(Math.abs(ang)>Math.PI/3*.7)return null;let ray=Math.floor((ang/(Math.PI/3)+.5)*200);return{x:W/2+ang/(Math.PI/3)*W,y:H/2,size:Math.min(H*1.2,H/sx)*o.size,dist:sx,ray}}
function vis(q){if(!q||q.ray<0||q.ray>=200)return false;return q.dist<=depth[q.ray]+.15}
function drawGob(e,q){let s=q.size;x.save();x.translate(q.x,H/2);x.globalAlpha=Math.max(.25,1-q.dist/18);x.fillStyle='#263026';x.fillRect(-s*.23,s*.48,s*.15,s*.34);x.fillRect(s*.08,s*.48,s*.15,s*.34);x.fillStyle=e.col;x.beginPath();x.ellipse(0,s*.18,s*.43,s*.5,0,0,7);x.fill();x.fillStyle='#78b64a';x.beginPath();x.ellipse(0,-s*.33,s*.42,s*.34,0,0,7);x.fill();x.beginPath();x.moveTo(-s*.28,-s*.4);x.lineTo(-s*.7,-s*.62);x.lineTo(-s*.34,-s*.16);x.fill();x.beginPath();x.moveTo(s*.28,-s*.4);x.lineTo(s*.7,-s*.62);x.lineTo(s*.34,-s*.16);x.fill();x.fillStyle='#ffe36a';x.fillRect(-s*.19,-s*.4,s*.11,s*.09);x.fillRect(s*.08,-s*.4,s*.11,s*.09);if(e.atk>0){x.strokeStyle='rgba(255,190,80,.8)';x.lineWidth=Math.max(2,s*.04);x.beginPath();x.arc(0,s*.08,s*.7,-1.1+Math.sin(e.atk*20),1.1+Math.sin(e.atk*20));x.stroke()}x.restore()}
function drawChest(o){let q=proj({x:o.x+.5,y:o.y+.5,size:.35});if(!vis(q))return;x.save();x.translate(q.x,H/2+q.size*.25);x.fillStyle='#5b331c';x.fillRect(-q.size*.45,-q.size*.1,q.size*.9,q.size*.5);x.fillStyle='#c18136';x.fillRect(-q.size*.45,-q.size*.1,q.size*.9,q.size*.1);x.fillStyle='#e2b94e';x.fillRect(-q.size*.08,0,q.size*.16,q.size*.17);if(!o.open){x.fillStyle='#8a5225';x.fillRect(-q.size*.42,-q.size*.4,q.size*.84,q.size*.28)}else{x.strokeStyle='#d09a46';x.strokeRect(-q.size*.42,-q.size*.4,q.size*.84,q.size*.28)}x.restore()}
function drawDrops(){for(const d of drops){let q=proj({x:d.x,y:d.y,size:.16});if(!vis(q))continue;x.fillStyle=d.t==='hp'?'#55ff9a':'#55d9ff';x.shadowBlur=15;x.shadowColor=x.fillStyle;x.fillRect(q.x-q.size/2,H/2-q.size/2,q.size,q.size);x.shadowBlur=0}}
function attack(){if(!run||p.cd>0||p.en<12)return;p.cd=p.rate;p.en-=12;flash=.08;let best=null,bd=2.7;for(const e of enemies){let dx=e.x-p.x,dy=e.y-p.y,d=Math.hypot(dx,dy),a=Math.atan2(dy,dx)-p.a;while(a>Math.PI)a-=2*Math.PI;while(a<-Math.PI)a+=2*Math.PI;if(d<bd&&Math.abs(a)<.28&&los(p.x,p.y,e.x,e.y)){best=e;bd=d}}if(best){let dmg=p.dmg*(Math.random()<p.crit?2:1);best.hp-=dmg;for(let i=0;i<10;i++)parts.push({x:best.x,y:best.y,vx:rnd(-1.5,1.5),vy:rnd(-1.5,1.5),life:.4,c:'#9deaff'})}for(let i=0;i<8;i++)parts.push({x:p.x+Math.cos(p.a)*.4,y:p.y+Math.sin(p.a)*.4,vx:Math.cos(p.a)*rnd(1,2),vy:Math.sin(p.a)*rnd(1,2),life:.25,c:'#8ce8ff'})}
function interact(){let b=null,bd=1.4;for(const d of doors){let z=Math.hypot(d.x+.5-p.x,d.y+.5-p.y);if(z<bd){b=d;bd=z}}if(b){b.open=b.open>.5?0:1;msg(b.open?'Kapı açıldı':'Kapı kapandı');return}for(const q of chests)if(!q.open&&Math.hypot(q.x+.5-p.x,q.y+.5-p.y)<1.3){q.open=true;let r=Math.random();if(r<.34){p.hp=Math.min(p.max,p.hp+35);msg('Sandık: +35 HP')}else if(r<.67){p.en=Math.min(100,p.en+45);msg('Sandık: +45 enerji')}else{p.dmg+=8;msg('Sandık: +8 saldırı gücü')}return}}
function move(dt){let f=(keys.KeyW?1:0)-(keys.KeyS?1:0),s=(keys.KeyD?1:0)-(keys.KeyA?1:0),l=Math.hypot(f,s);if(l){f/=l;s/=l}let sp=p.spd*dt*(keys.ShiftLeft||keys.ShiftRight?1.55:1);let ca=Math.cos(p.a),sa=Math.sin(p.a),dx=(f*ca-s*sa)*sp,dy=(f*sa+s*ca)*sp;if(!solid(p.x+dx,p.y))p.x+=dx;if(!solid(p.x,p.y+dy))p.y+=dy;if(mx){p.a+=mx*.0025;mx=0}p.en=Math.min(100,p.en+14*dt)}
function enemiesTick(dt){for(const e of enemies){e.atk=Math.max(0,e.atk-dt);let dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy);if(d>.75&&los(e.x,e.y,p.x,p.y)){let vx=dx/d*e.spd*dt,vy=dy/d*e.spd*dt;if(!solid(e.x+vx,e.y))e.x+=vx;if(!solid(e.x,e.y+vy))e.y+=vy}else if(d<=.75&&!e.atk){e.atk=.35;p.hp-=e.dmg;shake=5;if(p.hp<=0)return die()}}
 enemies=enemies.filter(e=>{if(e.hp>0)return true;kills++;gain(e.xp);if(Math.random()<.2)drops.push({x:e.x,y:e.y,t:Math.random()<.5?'hp':'en'});return false});if(!enemies.length){floor++;msg('Yeni kat: '+floor);makeMap()}}
function gain(n){xp+=n;if(xp>=need){xp-=need;level++;need=Math.floor(need*1.3);p.max+=15;p.hp=p.max;p.dmg+=5;msg('LEVEL UP! +15 HP +5 güç')}}
function particles(dt){for(const q of parts){q.x+=q.vx*dt;q.y+=q.vy*dt;q.life-=dt;let z=proj({x:q.x,y:q.y,size:.06});if(vis(z)){x.fillStyle=q.c;x.fillRect(z.x,z.y,z.size,z.size)}}parts=parts.filter(q=>q.life>0)}
function hud(){ $('level').textContent='LV '+level;$('xpText').textContent=`${xp|0} / ${need} XP`;$('kills').textContent=kills;$('floor').textContent=floor;$('hpFill').style.width=Math.max(0,p.hp/p.max*100)+'%';$('hpText').textContent=`${Math.max(0,p.hp|0)} / ${p.max}`;$('energyFill').style.width=p.en+'%';$('energyText').textContent=p.en|0}
function msg(t){$('message').textContent=t;msgT=1.5}
function render(dt){x.save();if(shake){x.translate(rnd(-shake,shake),rnd(-shake,shake));shake*=.85}cast();drawDrops();for(const q of chests)drawChest(q);for(const e of enemies){let q=proj(e);if(vis(q))drawGob(e,q)}particles(dt);if(flash){x.fillStyle=`rgba(140,235,255,${flash*3})`;x.fillRect(0,0,W,H);flash-=dt}x.restore();hud();if(msgT>0){msgT-=dt;$('message').style.opacity=Math.min(1,msgT*2)}else $('message').style.opacity=0}
function die(){run=false;$('deathStats').textContent=`Level ${level} · Floor ${floor} · ${kills} düşman`;$('death').classList.remove('hidden')}
function loop(t){if(!run)return;let dt=Math.min(.033,(t-last)/1000||.016);last=t;p.cd=Math.max(0,p.cd-dt);move(dt);enemiesTick(dt);render(dt);requestAnimationFrame(loop)}
addEventListener('keydown',e=>{keys[e.code]=1;if(e.code==='Space'){e.preventDefault();attack()}if(e.code==='KeyE')interact()});addEventListener('keyup',e=>keys[e.code]=0);addEventListener('mousemove',e=>{if(document.pointerLockElement===c)mx+=e.movementX});addEventListener('mousedown',e=>{if(e.button===0){if(document.pointerLockElement!==c)c.requestPointerLock?.();attack()}});
$('startBtn').onclick=()=>{$('startScreen').classList.add('hidden');$('death').classList.add('hidden');floor=1;kills=0;level=1;xp=0;need=100;p.hp=p.max=100;p.en=100;p.spd=1.8;p.dmg=34;p.rate=.38;p.cd=0;p.crit=.08;makeMap();run=true;last=performance.now();c.requestPointerLock?.();requestAnimationFrame(loop)};
$('restartBtn').onclick=()=>{$('death').classList.add('hidden');$('startScreen').classList.remove('hidden')};
makeMap();hud();
})();